// Code generated by protoc-gen-go-aip-cli. DO NOT EDIT.
package main

import (
	v1 "github.com/FreekingDean/proxmox-kubernetes-engine/cmd/pke/proxmox_kubernetes_engine/v1"
	cobra "github.com/spf13/cobra"
	aipcli "go.einride.tech/aip-cli/aipcli"
)

func NewModuleCommand(use string, short string, commands ...*cobra.Command) *cobra.Command {
	config := NewConfig()
	return aipcli.NewModuleCommand(
		use,
		short,
		config,
		append(
			[]*cobra.Command{
				v1.NewClusterServiceCommand(config),
				v1.NewMachinePoolAssignmentServiceCommand(config),
				v1.NewMachinePoolServiceCommand(config),
				v1.NewMachineServiceCommand(config),
			},
			commands...,
		)...,
	)
}

func NewConfig() aipcli.Config {
	return aipcli.Config{Hosts: map[string]string{}, DefaultHost: "", RootPath: "", Root: "main", GoogleCloudIdentityTokens: false, CachedIdentityTokenPath: ""}
}
